### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by kpoots** [awaisathar/dependensee#3]
Thank you for your patience with my request. I'm learning about dependency parsing. 
Your graphical tool is great ! Thank you for coding. 

For dependency parsing, an option for the parser which forces some verbs to be the parse tree root is "makeCopulaHead" ; works nicely for the stanford demo.
I was wondering if there was any way to incorporate "makeCopulaHead" as an option which you pass to the parser before you create your .png ? 

For example, the parse for the sentence "The apple is red." becomes:
det(apple-3, The-2)
nsubj(is-4, apple-3)
root(ROOT-0, is-4)
acomp(is-4, red-5)

instead of:
det(apple-3, The-2)
nsubj(red-5, apple-3)
cop(red-5, is-4)
root(ROOT-0, red-5)

There seems to be school of thought which says that dependency trees should start with a verb if possible. 

Thanks for any feedback !
Kent

**Comment by awaisathar** [comment]
You can perhaps use the same mechanism as http://stackoverflow.com/questions/26525859/activate-makecopulahead-in-stanford-corenlp-parser
